# fly -t tutorial execute -c tasks/hello_world.yml

---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: amazonlinux
    tag: "2"

run:
  path: bash
  args:
    - -exc
    - |
      pwd
      ls -al
      echo "hello world"
