# fly -t tutorial execute -c tasks/hello_world.yml

---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: amazonlinux
    tag: "2"

run:
  # path: custom-tasks/tasks/hello_world_2.sh
  path: bash
  args:
    - -exc
    - |
      ls -al
      ls -al local-dir/

