# fly -t tutorial e -c run_script_1.yml
# since the tasks dir is being passed in as `tasks`, it will run the script in that DIR

---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: amazonlinux
    tag: "2"

inputs:
  - name: tasks

run:
  path: ./tasks/run_script_1.sh
