---
resources:
  - name: tutorial
    type: git
    source:
      uri: https://github.com/gkspranger/hackconcourse.git
      branch: master

jobs:
  - name: create-output
    public: true
    plan:
      - get: tutorial
        trigger: true

      # creates some-files output
      - task: create-output
        file: tutorial/tasks/output_1.yml
        input_mapping:
          custom-tasks: tutorial

      - task: use-output
        input_mapping:
          files: some-files   # look at me ma !!
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: amazonlinux
              tag: "2"
          run:
            path: bash
            args:
              - -exc
              - |
                pwd
                ls -al
                ls -al files/
                echo "hello world"
